# Generated by Django 3.2.7 on 2021-10-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='times_followed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
