# Generated by Django 3.2.7 on 2021-10-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_link_times_followed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='shortened_link',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
